# Use faster registry mirror for better performance
npmRegistryServer: "https://registry.yarnpkg.com"

# Enable global cache to speed up installs
enableGlobalCache: true

# Timeout settings for network issues
httpTimeout: 60000
networkTimeout: 60000

# Retry settings for network failures
networkConcurrency: 8
