[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[functions]
  directory = "netlify/functions"

# Note: Scheduled functions require Netlify Pro plan
# For manual testing, use: /.netlify/functions/cleanup-expired
# For scheduled cleanup: /.netlify/functions/cleanup

# Uncomment below if you have Netlify Pro:
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

# Scheduled cleanup of expired unclaimed posts (daily at midnight UTC)
[[plugins.inputs.functions]]
  name = "cleanup"
  cron = "0 0 * * *"

# Alternative: hourly cleanup for more aggressive cleaning
# [[plugins.inputs.functions]]
#   name = "cleanup-expired"
#   cron = "0 * * * *"

# Redirects for blog posts
[[redirects]]
  from = "/blog/:slug"
  to = "/blog/index.html?slug=:slug"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variable settings
[context.production.environment]
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
