[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  publish = "dist"
  command = "yarn build"

# Headers for security and permissions
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "clipboard-write=(self)"

[dev]
  command = "yarn dev"
  targetPort = 8080
  port = 8888

[functions]
  directory = "netlify/functions"

# Note: Scheduled functions are now configured directly in function files
# using the schedule() function from @netlify/functions
# For manual testing, use: /.netlify/functions/cleanup-expired

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Domain-specific blog content routing for leadpages.org
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/domain-blog-server"
  status = 200
  conditions = {Host = ["leadpages.org"]}

# Domain-specific blog content routing for other blog domains
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/domain-blog-server"
  status = 200
  conditions = {Host = ["backlinks.org", "seo-tools.org"]}

# Individual blog post routing for domains
[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/blog-post-server?slug=:splat"
  status = 200
  conditions = {Host = ["leadpages.org", "backlinks.org", "seo-tools.org"]}

# SPA fallback - this handles all routes for the admin interface
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Configure secrets scanning
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "true"
  # Skip scanning specific files that contain example/demo secrets
  SECRETS_SCAN_SMART_DETECTION_OMIT_PATHS = "*.md,EMERGENCY_FIX_NOW.md,EMAIL_CONFIGURATION_COMPLETE.md,OPENAI_API_KEY_SETUP.md,test-*.html,test-*.js"

# Environment variable settings
[context.production.environment]
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
