[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[functions]
  directory = "netlify/functions"

# Note: Scheduled functions are now configured directly in function files
# using the schedule() function from @netlify/functions
# For manual testing, use: /.netlify/functions/cleanup-expired

# Redirects for blog posts
[[redirects]]
  from = "/blog/:slug"
  to = "/blog/index.html?slug=:slug"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variable settings
[context.production.environment]
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
