// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get Supabase configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('🔧 Supabase client configuration:', {
  hasUrl: !!SUPABASE_URL,
  hasKey: !!SUPABASE_ANON_KEY,
  url: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : 'missing',
  keyPrefix: SUPABASE_ANON_KEY ? SUPABASE_ANON_KEY.substring(0, 10) + '...' : 'missing'
});

// Validate credentials
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
  throw new Error('Invalid Supabase URL format');
}

if (!SUPABASE_ANON_KEY.startsWith('eyJ') || SUPABASE_ANON_KEY.length < 100) {
  throw new Error('Invalid Supabase API key format');
}

// Create clean Supabase client without custom fetch to avoid stream conflicts
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'supabase.auth.token',
  },
  global: {
    headers: {
      'X-Client-Info': 'backlink-infinity@1.0.0',
    },
    // Use default fetch - no custom wrapper to avoid stream conflicts
  },
});

// Global network error handler for development
const handleNetworkError = (error: any, context: string) => {
  if (error && typeof error === 'object' && (
    error.message?.includes('Failed to fetch') ||
    error.message?.includes('NetworkError') ||
    error.message?.includes('fetch is not defined') ||
    error.message?.includes('ENOTFOUND') ||
    error.message?.includes('ECONNREFUSED')
  )) {
    console.warn(`⚠️ Network error in ${context}:`, error.message);
    return true; // Indicates this was a network error
  }
  return false; // Not a network error
};

// Test connection in development
if (import.meta.env.DEV) {
  setTimeout(async () => {
    try {
      console.log('🔍 Testing Supabase connection...');
      const { data, error } = await supabase
        .from('domains')
        .select('id')
        .limit(1);

      if (error) {
        if (!handleNetworkError(error, 'connection test')) {
          console.warn('⚠️ Database connection test failed:', error.message);
        }
      } else {
        console.log('✅ Supabase connection test successful');
      }
    } catch (testError: any) {
      if (!handleNetworkError(testError, 'connection test')) {
        console.warn('⚠️ Supabase connection test error:', testError.message);
      }
    }
  }, 1000);
}

// Export the network error handler for use in other parts of the app
export { handleNetworkError };

console.log('✅ Clean Supabase client initialized');
